/* Generated by generate_connectivity_fixtures.py; do not edit. */
#ifndef GPIO_CONNECTIVITY_MPU_REPLAY_H
#define GPIO_CONNECTIVITY_MPU_REPLAY_H

#include <stddef.h>

#ifndef GPIO_CONNECTIVITY_REPLAY_TYPES_H
#define GPIO_CONNECTIVITY_REPLAY_TYPES_H
typedef struct {
    const char *controller;
    const char *signal;
    unsigned vector_index;
    const char *command_kind;
    int drive_value;
    int expected_value;
} gpio_connectivity_replay_command_t;
#endif

static const gpio_connectivity_replay_command_t gpio_connectivity_mpu_replay[] = {
    {"mpu", "mpu_uart_tx_to_fpga_rx", 0u, "drive", 0, 0},
    {"mpu", "mpu_uart_tx_to_fpga_rx", 1u, "drive", 1, 1},
    {"mpu", "fpga_uart_tx_to_mpu_rx", 2u, "sample_expect", 0, 0},
    {"mpu", "fpga_uart_tx_to_mpu_rx", 3u, "sample_expect", 1, 1},
    {"mpu", "mpu_reset_output_to_fpga_reset_n", 4u, "drive", 0, 0},
    {"mpu", "mpu_reset_output_to_fpga_reset_n", 5u, "drive", 1, 1},
    {"mpu", "mpu_control_output_to_fpga_ctrl_start", 6u, "drive", 0, 0},
    {"mpu", "mpu_control_output_to_fpga_ctrl_start", 7u, "drive", 1, 1},
    {"mpu", "fpga_ready_status_to_mpu_status_input", 8u, "sample_expect", 0, 0},
    {"mpu", "fpga_ready_status_to_mpu_status_input", 9u, "sample_expect", 1, 1},
    {"mpu", "mpu_qspi_clk_to_fpga_sclk", 10u, "drive", 0, 0},
    {"mpu", "mpu_qspi_clk_to_fpga_sclk", 11u, "drive", 1, 1},
    {"mpu", "mpu_qspi_ncs_to_fpga_cs_n", 12u, "drive", 0, 0},
    {"mpu", "mpu_qspi_ncs_to_fpga_cs_n", 13u, "drive", 1, 1},
    {"mpu", "mpu_qspi_io0_to_fpga_io0", 14u, "drive", 0, 0},
    {"mpu", "mpu_qspi_io0_to_fpga_io0", 15u, "drive", 1, 1},
    {"mpu", "mpu_qspi_io0_to_fpga_io0", 16u, "sample_expect", 0, 0},
    {"mpu", "mpu_qspi_io0_to_fpga_io0", 17u, "sample_expect", 1, 1},
    {"mpu", "mpu_qspi_io1_to_fpga_io1", 18u, "drive", 0, 0},
    {"mpu", "mpu_qspi_io1_to_fpga_io1", 19u, "drive", 1, 1},
    {"mpu", "mpu_qspi_io1_to_fpga_io1", 20u, "sample_expect", 0, 0},
    {"mpu", "mpu_qspi_io1_to_fpga_io1", 21u, "sample_expect", 1, 1},
    {"mpu", "mpu_qspi_io2_to_fpga_io2", 22u, "drive", 0, 0},
    {"mpu", "mpu_qspi_io2_to_fpga_io2", 23u, "drive", 1, 1},
    {"mpu", "mpu_qspi_io2_to_fpga_io2", 24u, "sample_expect", 0, 0},
    {"mpu", "mpu_qspi_io2_to_fpga_io2", 25u, "sample_expect", 1, 1},
    {"mpu", "mpu_qspi_io3_to_fpga_io3", 26u, "drive", 0, 0},
    {"mpu", "mpu_qspi_io3_to_fpga_io3", 27u, "drive", 1, 1},
    {"mpu", "mpu_qspi_io3_to_fpga_io3", 28u, "sample_expect", 0, 0},
    {"mpu", "mpu_qspi_io3_to_fpga_io3", 29u, "sample_expect", 1, 1},
};
static const size_t gpio_connectivity_mpu_replay_count = sizeof(gpio_connectivity_mpu_replay) / sizeof(gpio_connectivity_mpu_replay[0]);

#endif /* GPIO_CONNECTIVITY_MPU_REPLAY_H */
