#!/usr/bin/env python3
import argparse
import json
import sys
from pathlib import Path


BASE = Path(__file__).resolve().parent
SCRIPTS = {
    "mpu": BASE / "connectivity_mpu.jsonl",
    "fpga": BASE / "connectivity_fpga.jsonl",
}
OUTPUTS = {
    "mpu": BASE / "connectivity_mpu_replay.h",
    "fpga": BASE / "connectivity_fpga_replay.h",
}
VALID_OPS = {"drive", "sample_expect"}
REQUIRED_FIELDS = {
    "controller",
    "signal",
    "vector_index",
    "op",
    "drive_value",
    "expected_value",
}


class FixtureError(ValueError):
    pass


def require_bit(command, field, path, line_number):
    value = command.get(field)
    if isinstance(value, bool) or value not in {0, 1}:
        raise FixtureError(f"{path}:{line_number}: {field} must be 0 or 1")
    return value


def validate_command(command, controller, path, line_number):
    fields = set(command)
    missing = REQUIRED_FIELDS - fields
    extra = fields - REQUIRED_FIELDS
    if missing or extra:
        details = []
        if missing:
            details.append(f"missing {sorted(missing)}")
        if extra:
            details.append(f"extra {sorted(extra)}")
        raise FixtureError(f"{path}:{line_number}: bad command fields: {'; '.join(details)}")

    if command["controller"] != controller:
        raise FixtureError(
            f"{path}:{line_number}: controller {command['controller']!r} "
            f"does not match script {controller!r}"
        )
    if command["op"] not in VALID_OPS:
        raise FixtureError(f"{path}:{line_number}: unknown op {command['op']!r}")
    if not isinstance(command["signal"], str) or not command["signal"]:
        raise FixtureError(f"{path}:{line_number}: signal must be a non-empty string")
    vector_index = command["vector_index"]
    if isinstance(vector_index, bool) or not isinstance(vector_index, int) or vector_index < 0:
        raise FixtureError(f"{path}:{line_number}: vector_index must be a non-negative int")
    require_bit(command, "drive_value", path, line_number)
    require_bit(command, "expected_value", path, line_number)


def load_script(path, controller):
    commands = []
    for line_number, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        try:
            command = json.loads(line)
        except json.JSONDecodeError as exc:
            raise FixtureError(f"{path}:{line_number}: invalid JSON: {exc}") from exc
        if not isinstance(command, dict):
            raise FixtureError(f"{path}:{line_number}: command must be an object")
        validate_command(command, controller, path, line_number)
        commands.append(command)
    return commands


def load_scripts(scripts=SCRIPTS):
    return {
        controller: load_script(path, controller)
        for controller, path in scripts.items()
    }


def c_string(value):
    return json.dumps(value, ensure_ascii=True)


def macro_name(controller):
    return f"GPIO_CONNECTIVITY_{controller.upper()}_REPLAY_H"


def array_name(controller):
    return f"gpio_connectivity_{controller}_replay"


def render_header(controller, commands):
    guard = macro_name(controller)
    array = array_name(controller)
    lines = [
        "/* Generated by generate_connectivity_fixtures.py; do not edit. */",
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        "#include <stddef.h>",
        "",
        "#ifndef GPIO_CONNECTIVITY_REPLAY_TYPES_H",
        "#define GPIO_CONNECTIVITY_REPLAY_TYPES_H",
        "typedef struct {",
        "    const char *controller;",
        "    const char *signal;",
        "    unsigned vector_index;",
        "    const char *command_kind;",
        "    int drive_value;",
        "    int expected_value;",
        "} gpio_connectivity_replay_command_t;",
        "#endif",
        "",
        f"static const gpio_connectivity_replay_command_t {array}[] = {{",
    ]
    for command in commands:
        lines.append(
            "    {"
            f"{c_string(command['controller'])}, "
            f"{c_string(command['signal'])}, "
            f"{command['vector_index']}u, "
            f"{c_string(command['op'])}, "
            f"{command['drive_value']}, "
            f"{command['expected_value']}"
            "},"
        )
    lines.extend(
        [
            "};",
            f"static const size_t {array}_count = sizeof({array}) / sizeof({array}[0]);",
            "",
            f"#endif /* {guard} */",
            "",
        ]
    )
    return "\n".join(lines)


def expected_outputs(scripts=None):
    loaded = load_scripts(SCRIPTS if scripts is None else scripts)
    return {
        controller: render_header(controller, commands)
        for controller, commands in loaded.items()
    }


def write_outputs(outputs):
    for controller, contents in outputs.items():
        OUTPUTS[controller].write_text(contents, encoding="utf-8")


def check_outputs(outputs):
    stale = []
    for controller, expected in outputs.items():
        path = OUTPUTS[controller]
        try:
            actual = path.read_text(encoding="utf-8")
        except FileNotFoundError:
            stale.append(f"{path}: missing")
            continue
        if actual != expected:
            stale.append(f"{path}: stale")
    return stale


def main(argv=None):
    parser = argparse.ArgumentParser(
        description="Generate first-pass GPIO connectivity replay fixtures."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if generated replay fixture headers are missing or stale",
    )
    args = parser.parse_args(argv)

    try:
        outputs = expected_outputs()
    except FixtureError as exc:
        print(f"connectivity fixture generation failed: {exc}", file=sys.stderr)
        return 1

    if args.check:
        stale = check_outputs(outputs)
        if stale:
            for item in stale:
                print(item, file=sys.stderr)
            return 1
        print("connectivity replay fixtures are current")
        return 0

    write_outputs(outputs)
    for path in OUTPUTS.values():
        print(path)
    return 0


if __name__ == "__main__":
    sys.exit(main())
